### ISSUE TITLE
Stuck in Violet City

### ISSUE THREAD

**Issue by vicendithas** [pclalv/crystal-key-item-randomizer#2]
I was playing a seed with the end condition as Elite Four and with Badge Randomization active. I beat Faulkner and received the Thunder Badge, but when I tried to leave Violet to the south, the guy that forces you back to do the gym still wouldn't let me pass. I haven't had this problem before when my end condition was Defeat Red.

**Comment by pclalv** [comment]
if you get the egg from Elm's aide at the Violet Pokemon Center, then you're able to get past that guy that forces you back. 

however, you bring up a good point - the interaction that you saw was confusing. i fixed that in https://github.com/pclalv/crystal-key-item-randomizer/commit/90481c66671b0ceebc43b55437d81b254c07a3df by changing the code to check that the player has beaten Falkner instead of checking that the player has the Zephyr Badge. this way, the player doesn't have to get the egg.
